/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package country_codes;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testForBY() {
        App classUnderTest = new App();
        assertEquals(true, App.runDEA("BY"));
    }

    @Test
    public void testForBW() {
        App classUnderTest = new App();
        assertEquals(true, App.runDEA("BW"));
    }

    @Test
    public void testForWrong() {
        App classUnderTest = new App();
        assertEquals(false, App.runDEA("BT"));
    }

    @Test
    public void testForTooLong() {
        App classUnderTest = new App();
        assertEquals(false, App.runDEA("BTYX"));
    }

    @Test

    public void testForNotAllowedChars() {
        App classUnderTest = new App();
        assertEquals(false, App.runDEA("BY!"));
    }
}
